import { MainNav } from "@/components/main-nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Image from "next/image";
import Icon from "@/components/desktop/Icon";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Briefcase, Laptop2, StickyNote, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";

const desktopIcons = [
  {
    id: 1,
    label: "My Computer",
    icon: <Laptop2 className="w-10 h-10 text-windows-dark" />,
  },
  {
    id: 2,
    label: "My Briefcase",
    icon: <Briefcase className="w-10 h-10 text-amber-800" />,
  },
  {
    id: 3,
    label: "Recycle Bin",
    icon: <Trash2 className="w-10 h-10 text-windows" />,
  },
  {
    id: 4,
    label: "Notepad",
    icon: <StickyNote className="w-10 h-10 text-windows-blue" />,
  },
];

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          `bg-gradient-to-br from-sky-300 to-sky-600 relative h-screen overflow-hidden`,
          inter.className
        )}
      >
        <div className="absolute top-0 left-0 flex flex-col items-center justify-evenly">
          {desktopIcons.map((icon) => (
            <Dialog key={icon.id}>
              <DialogTrigger asChild>
                <Icon icon={icon.icon} label={icon.label} />
              </DialogTrigger>
              <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                  <DialogTitle>Edit profile</DialogTitle>
                  <DialogDescription></DialogDescription>
                </DialogHeader>
                {/* <div></div> */}
                <DialogFooter>
                  <Button type="submit">Save changes</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          ))}
        </div>
        <div className="relative grid w-1/3 h-screen mx-auto -z-0 place-items-center">
          <Image src="/download.png" alt="" height={200} width={200} />
        </div>
        {children}
        <MainNav />
      </body>
    </html>
  );
}
