export const siteConfig = {
  description:
    "Explore my Windows 98-inspired portfolio blending modern development skills with a nostalgic twist.",
  keywords: [
    "jccdev",
    "Jordan Cruz-Correa",
    "software engineer",
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "TailwindCSS",
    "shadcn-ui",
    "full-stack developer",
    "frontend developer",
    "web development",
    "UI/UX design",
    "responsive design",
    "Windows 98 inspired",
    "retro tech",
    "portfolio",
    "Supabase",
    "Node.js",
    "PostgreSQL",
    "Git",
    "GitHub",
    "Vercel",
    "Netlify",
  ],
  creator: "Jordan Cruz-Correa",
  author: "jccdev",
  openGraph: {
    title: "jccdev Portfolio",
    description:
      "Explore my Windows 98-inspired portfolio blending modern development skills with a nostalgic twist.",
    url: "https://jccdev.vercel.app",
    siteName: "jccdev Portfolio",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "jccdev Portfolio",
    description:
      "Explore my Windows 98-inspired portfolio blending modern development skills with a nostalgic twist.",
    creator: "@jccdev",
    images: ["https://jccdev.vercel.app/opengraph-image.jpg"],
  },
}
